#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'anro4','console_scripts','op_client'
__requires__ = 'anro4'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('anro4', 'console_scripts', 'op_client')()
    )
